### ISSUE TITLE
console.log does not exists in production

### ISSUE THREAD

**Issue by cbleek** [cross-solution/cross-solution.de#13]
leads to the problem:

https://travis-ci.org/cross-solution/cross-solution.de/builds/620230635#L345

Posibilities to solve the problem:

https://www.codebyamir.com/blog/suppressing-console-log-messages-in-production

**Comment by TiSiE** [comment]
This looks way more promising:

https://github.com/quasarframework/quasar/issues/5529

I will try this approach
