### ISSUE TITLE
Contact-Formular

### ISSUE THREAD

**Issue by Steinbach2019** [cross-solution/cross-solution.de#15]
adjustings for Contact-Formular

**Comment by cbleek** [comment]
I don't understand the issue and closing it.

Feel free to explain and reopen

**Comment by Steinbach2019** [comment]
Contact Form need to be adapted for col-xs flex. Desktop setting is now ok, mobile view should be extended to col-xs.

**Comment by cbleek** [comment]
OK

**Comment by Steinbach2019** [comment]
the changes done and waiting for ok to commit

**Comment by Steinbach2019** [comment]
commited and pushed to master
