### ISSUE TITLE
use card layout on mobile by default

### ISSUE THREAD

**Issue by cbleek** [cross-solution/cross-solution.de#17]
https://cross-solution.de/jobs contains parameter to switch between table and card layout.

The parameter "grid" is [set to false](https://github.com/cross-solution/cross-solution.de/blob/master/src/components/Jobsearch.vue#L149
) by default.

I would like to set git=true on mobile by default.

Here is the documentation how quasar is detecting the platform.

https://quasar.dev/options/platform-detection

/cc @TiSiE @Steinbach2019

**Comment by development0261** [comment]
OK. I understand the task. I will manage it.

**Comment by cbleek** [comment]
works on my mobile:-)
