### ISSUE TITLE
CoverPage + Yellow Box Notification

### ISSUE THREAD

**Issue by Steinbach2019** [cross-solution/cross-solution.de#18]
**Target:** Cross Solution Homepage get started and we get the blue coverPage animated and the
notification Yellow Box. We should try to program this two elements the way it will be appear only one time and then the both elements will be set on display: none. 

![grafik](https://user-images.githubusercontent.com/55985319/70154635-2391c680-16b1-11ea-83b0-348e516e29bb.png)
![grafik](https://user-images.githubusercontent.com/55985319/70154776-58058280-16b1-11ea-8def-fcef6267ce09.png)

**Comment by cbleek** [comment]
the GDPR Cookie popup [sets a Cookie](https://github.com/cross-solution/cross-solution.de/blob/master/src/boot/gdpr.js#L14). 

The code is executed, because it's configured in [quasar.conf.js](https://github.com/cross-solution/cross-solution.de/blob/master/quasar.conf.js#L12), I guess.

@development0261 can you try to set another Cookie, so the blue Coverpage and the orange Notification box appears only once?

**Comment by development0261** [comment]
OK. I am checking the requirement.
Thanks.

**Comment by Hetal2425** [comment]
@cbleek :Means If the user reopen the same window then it will not show next time.right?

If the user don't accept the cookie then also we need to do that?

**Comment by cbleek** [comment]
Yes. If the user does not accept cookies, we must not set cookies.  Then the user will see the splash page again and again.

**Comment by Hetal2425** [comment]
@cbleek Ok ,In the case of yellow box you need to manage like once the user open the page need to set one cookie and check next time that cookie is set or not.If cookie is not set then we need to show the boxes.Right?

**Comment by development0261** [comment]
@cbleek ,
Waiting for your reply.

**Comment by cbleek** [comment]
sorry, missed the question.

Yes

**Comment by development0261** [comment]
OK @cbleek Thanks.
Right now it's about closing time.
I will manage the things by tomorrow.
Have a great day ahead.

**Comment by Hetal2425** [comment]
Hi @cbleek 

I have completed the requested changes.

Could you please check that.

PR is : https://github.com/cross-solution/cross-solution.de/pull/24

**Comment by Hetal2425** [comment]
Hi @cbleek

Have you checked the changes.

**Comment by cbleek** [comment]
we should discuss all things concerning the PR within the [PR](https://github.com/cross-solution/cross-solution.de/pull/24) .

I've send you a PR too. Please merge it. It should fix the conflict

**Comment by cbleek** [comment]
well done. Thank you
