### ISSUE TITLE
Create components for editing a job ad layout.

### ISSUE THREAD

**Issue by TiSiE** [cross-solution/cross-solution.de#26]
From #25:

* Create a component for the data input (left side) [ in /src/components/Form/]
* Create a component for the preview (right side) [ in /src/components/Form/]
* The preview should update with live data from the inputs. (So the proper data-bindings must be used.)

![crossde-post-a-job-step2](https://user-images.githubusercontent.com/2029304/70438753-c621bf00-1a8e-11ea-8864-b17a0f449b5d.png)

**Comment by cbleek** [comment]
@Hetal2425 do you understand this Issue?

Can you do this? If so, feel free to assign it to yourself.

**Comment by Hetal2425** [comment]
@cbleek :Means I need to display the dynamic content to right hand side.Right?

Right now there is two inputs like editor and contact box on left hand side.In these which details you need to display on right hand side?

**Comment by cbleek** [comment]
yes. Display the dynamic content to right hand side.Right

there two input field (boderless), which can be edited and wich should be shown on the right side

![Auswahl_380](https://user-images.githubusercontent.com/858642/70515280-5fa3ac00-1b35-11ea-88ea-023d7547ef30.png)

**Comment by Hetal2425** [comment]
@cbleek  : Yes I got it. I will Manage that.

**Comment by Hetal2425** [comment]
I have solved the issues.

Please find the attached Pull request.

https://github.com/cross-solution/cross-solution.de/pull/28

**Comment by cbleek** [comment]
It works. But there is no Component anymore. We wanted to break the long post-a-job.vue into smaller peaces.

Can you undo the changes. Please figgure out, how to pass data between components.

Maybe this helps.

https://medium.com/@andrejsabrickis/https-medium-com-andrejsabrickis-create-simple-eventbus-to-communicate-between-vue-js-components-cdc11cd59860

**Comment by Hetal2425** [comment]
Hi @cbleek : Ok I will check and do the needful.

**Comment by cbleek** [comment]
@Hetal2425 

maybe we should should move the complete "q-splitter" Section to the [Job Component](https://github.com/cross-solution/cross-solution.de/blob/master/src/components/Form/Job.vue). This way we split the long "post-a-job" into smaller peaces and the preview will work without figuring out, how to share variables betrween components.

Can you try do do it this way?

**Comment by Hetal2425** [comment]
@cbleek 

Yes. I will do that.

**Comment by Hetal2425** [comment]
@cbleek Working on the changes.

I will finish and push the code by Tomorrow.

**Comment by cbleek** [comment]
fine.

I prefer that you use the upwork clock instead of manual tracking.

**Comment by Hetal2425** [comment]
@cbleek I have completed the changes.

Moved q-splitter section to Job component. So directly get the variable values there.

If we need to share the variable between the components then also we can use the emit method to share the values.I have added that code in files.

Please check once and let me know if any changes you need.

**Comment by Hetal2425** [comment]
@cbleek 
Any other tasks?

**Comment by Hetal2425** [comment]
@cbleek : Any other tasks ?

**Comment by cbleek** [comment]
@TiSiE can you give hetal some feedback.

I've committed some code cleanups. 
https://github.com/cross-solution/cross-solution.de/commit/d87c28f03a98b2f69f418c769d7a26d0d3da6e31

**Comment by TiSiE** [comment]
I made a review of the pull request.

@Hetal2425 
Please be not offended. I may sound a bit harsh, but nevertheless I appreciate your work.

**Comment by Hetal2425** [comment]
@TiSiE Thank you.

But would you please let me know about my mistake ? So that I can take care at next time.

**Comment by cbleek** [comment]
You didn't make a mistake. Take a look at my Cleanup Commit.

https://github.com/cross-solution/cross-solution.de/commit/d87c28f03a98b2f69f418c769d7a26d0d3da6e31

Next time, take your time to improve the quality.

**Comment by cbleek** [comment]
@Hetal2425 feel free to [add yourself to the team](https://github.com/cross-solution/cross-solution.de/blob/ffdd2b8da0c68a5bd498846952949ab28cd52abc/src/pages/about.vue#L108)

A new Issue was created in #30
