### ISSUE TITLE
localize our app

### ISSUE THREAD

**Issue by cbleek** [cross-solution/cross-solution.de#30]
we want to localize our quasar app

https://quasar.dev/options/app-internationalization#Introduction

@Hetal2425 can you try to get the Browsers Locale and write "About us" in the top menu in case the locale is "en"?

![Auswahl_391](https://user-images.githubusercontent.com/858642/70981997-870af380-20b6-11ea-8f83-e7a6f275310b.png)

https://github.com/cross-solution/cross-solution.de/blob/master/src/layouts/CrossLayout.vue#L15

**Comment by development0261** [comment]
Hi @cbleek ,
I need to get local language of browser, if it's English then need to change label for **About Us**

Correct?

**Comment by cbleek** [comment]
By using the i18n stuff. Yes

Cross Solution           | Carsten Bleek
Diemelstraße 2-4         | Tel: 069-71910361
60486 Frankfurt am Main  | Fax: 069-71910369
http://cross-solution.de | bleek@cross-solution.de

**Comment by Hetal2425** [comment]
Hi @cbleek 

I have started to working on the task.

Facing some issues in i18n.

I will look the issues by tomorrow.

**Comment by cbleek** [comment]
+1

thank you

**Comment by development0261** [comment]
Hi @cbleek

I have made changes for this. For this task I have use a flag to check browser language. And when it detect en then it will display About Us. I have used two same components for this with v-if condition. Please check and let me know that I have made changes as you want or not?

I have tried to commit but do not know why my committing is not getting reflected to GitHub. So would you please check my commit access for repository?

I have done below changes.

	1:- I have made changes in src/layouts/CrossLayout.vue file.

		<q-btn-dropdown v-if="this.flag == -1" flat color="primary" label="Über uns">
            <q-list>
              <q-item clickable v-close-popup to="/about">
                <q-item-section>
                  <q-item-label>Team</q-item-label>
                </q-item-section>
              </q-item>

              <q-item clickable v-close-popup to="/values">
                <q-item-section>
                  <q-item-label>Werte</q-item-label>
                </q-item-section>
              </q-item>

              <q-item clickable v-close-popup to="/timeline">
                <q-item-section>
                  <q-item-label>Timeline</q-item-label>
                </q-item-section>
              </q-item>
            </q-list>
          </q-btn-dropdown>
          <q-btn-dropdown v-if="this.flag == 0" flat color="primary" label="About Us">
            <q-list>
              <q-item clickable v-close-popup to="/about">
                <q-item-section>
                  <q-item-label>Team</q-item-label>
                </q-item-section>
              </q-item>

              <q-item clickable v-close-popup to="/values">
                <q-item-section>
                  <q-item-label>Werte</q-item-label>
                </q-item-section>
              </q-item>

              <q-item clickable v-close-popup to="/timeline">
                <q-item-section>
                  <q-item-label>Timeline</q-item-label>
                </q-item-section>
              </q-item>
            </q-list>
          </q-btn-dropdown>

          **Note:- I have put above code for line number 15 to 56.**

        
		      flag: '-1'
		   

		  **Note:- Added above line at 175.**

		 mounted () {
		    if (this.$q.lang.getLocale().indexOf('en') === 0) {
		      this.flag = 0// If brownser lan is english
		    }
		    else {
		      this.flag = -1
		    }
		  }

		  **Note:- Added above code at line number 223 to 230**

**Comment by cbleek** [comment]
please push your changes into your fork and create a Pull Request.

https://guides.github.com/introduction/flow/

**Comment by cbleek** [comment]
But there must be a better solution than the "v-if" way.

See https://kazupon.github.io/vue-i18n/started.html#html

**Comment by cbleek** [comment]
Here is another starting point https://quasar.dev/options/app-internationalization

in the CrossLayout, the change will look something like this:

from: <q-btn-dropdown ...  label="Über uns">

to: <q-btn-dropdown ...  label=""{{ $t('Über uns') }}">

Maybe the language file are generated, if the vue-i18n-loader is added to the  extendWebpack in quasar.conf.js.

Please read the docs and give it a try

**Comment by rajeshp0261** [comment]
@cbleek I will try with above suggestions and inform you.

**Comment by development0261** [comment]
@cbleek I will try your suggestions and inform you.

**Comment by development0261** [comment]
@cbleek I have found another way to change about-us label according browser language.  
I have created pull request for this https://github.com/development0261/cross-solution.de fork. Please check.

**Comment by cbleek** [comment]
@development0261 if you fork the repo from @Hetal2425 , you are sending your pull requests to @Hetal2425 .

**Comment by development0261** [comment]
@cbleek Ok let me check.

**Comment by development0261** [comment]
I have created pull request from Hetal2425 / cross-solution.de fork. Please check pull request for this.

**Comment by Hetal2425** [comment]
Hi @cbleek ,
Ok will check it.
