### ISSUE TITLE
adding: cover page + design elements

### ISSUE THREAD

**Issue by Steinbach2019** [cross-solution/cross-solution.de#4]
1 - extra page/div container(animated) incl. the CROSS Logo
2 - adding 2 Fonts 
3 - Logo adjusting
4 - Products Boxes adjusting
5 - additional sections [ get in touch ]

**Comment by Steinbach2019** [comment]
@cbleek wie gehts weiter

**Comment by Steinbach2019** [comment]
Products Boxes should be adjusted to

**Comment by cbleek** [comment]
each team member in the [docs](https://quasar.dev/meet-the-team) uses a q-card.

They have all the same hight.

https://github.com/quasarframework/quasar/tree/dev/docs/src/components/page-parts/meet-the-team

**Comment by Steinbach2019** [comment]
Cover page now appears correkt. Adding z-index 3000 over header 2000
