### ISSUE TITLE
How do we store local Settings

### ISSUE THREAD

**Issue by cbleek** [cross-solution/cross-solution.de#54]
When running the app in electron, and clicking on the facebook button, the authentification does not work.

![Bildschirmfoto 2020-02-24 um 21 13 20](https://user-images.githubusercontent.com/858642/75187559-8f347e80-574a-11ea-92a1-59a250752d12.png)

This is probably because we set the app id  only in https://github.com/cross-solution/cross-solution.de/blob/master/src/boot/hello.js. An app secret is set nowhere. Maybe the auth is working in the web app (ssr:pwa mode) because facebook can determine a Hostname, which is sending requests. 

![Bildschirmfoto 2020-02-24 um 21 21 08](https://user-images.githubusercontent.com/858642/75188197-facb1b80-574b-11ea-8841-855ce6f2447f.png)

However. We have to answer the question, how to store user settings in an electron app.

@calmcalmdown do you have an idea?

**Comment by calmcalmdown** [comment]
@cbleek let me check first asap

**Comment by calmcalmdown** [comment]
Hi @cbleek I have logged in successfully.

**Comment by calmcalmdown** [comment]
first, setting with facebook developer account
http://prntscr.com/r76vc0

**Comment by calmcalmdown** [comment]
next, add APP_ID_FACEBOOK
http://prntscr.com/r76vtb

**Comment by calmcalmdown** [comment]
tested on my local, and worked for me.
http://prntscr.com/r76xiw

**Comment by cbleek** [comment]
But does it runs as an electron app?

**Comment by calmcalmdown** [comment]
@cbleek i found why it is not working. maybe we don't need the app secret.
![image](https://user-images.githubusercontent.com/44122665/75257524-26a2db80-57f6-11ea-8192-f1870f93a00a.png)
As you can see the client id(app id) is undefined

**Comment by cbleek** [comment]
But the headline of your screen shows "Google Chrome". Is the app running as an electron as described in:

https://cross-solution.de/download

**Comment by cbleek** [comment]
but you're right. The client_id seem's to be missing. I'f I clich on LinkedIn button running in electron mode I get the LinkedIn Response

`The passed in client_id is invalid "undefined"`

So the values defined in `.env` might be not inserted, when building the electron app.

**Comment by calmcalmdown** [comment]
@cbleek yeah, I think so

**Comment by cbleek** [comment]
However. The focus of this issue should be to think about how to store user settings.  These .env values are some kind of user settings, I guess.

**Comment by calmcalmdown** [comment]
@cbleek i have made .env.production file and tested app. there is another error, maybe it is from facebook app settings.

**Comment by calmcalmdown** [comment]
could you give me facebook app settings?

**Comment by calmcalmdown** [comment]
@cbleek 
please take a look at process.env.APP_URL in electron-main.js
![image](https://user-images.githubusercontent.com/44122665/75308192-d7dd5c00-585e-11ea-9fdc-41ee07922884.png)
I have tested on my local like the following steps.
- change process.env.APP_URL as http://localhost:8080
- build-win32
- run on localhost(yarn dev)
- run electron app
if then, electron app would be run as the localhost:8080(I am not sure, which is running without process.env.APP_URL value. I think, maybe it is running embedded source within the executable file ) I can't see above issues. how do you think?

**Comment by calmcalmdown** [comment]
@cbleek any update?

**Comment by cbleek** [comment]
I've added the the env in a page and it shows the localhost:8080 is used by default. If the Port is already in use, quasar seems to search the next available port. If you start the app twice, the second one uses 8081.

I'm willing to bet that OAuth will work if that secret is sent along.

Whatever. Let's close this issue and open a new one for the OAuth problem.

![Bildschirmfoto 2020-02-26 um 11 03 20](https://user-images.githubusercontent.com/858642/75380644-af457880-58d7-11ea-8b17-d9ffd4c074ea.png)
