### ISSUE TITLE
integrate calendly into our homepage

### ISSUE THREAD

**Issue by cbleek** [cross-solution/cross-solution.de#66]
@kilip

I would like to integrate calendly into our homepage. I've added it in https://github.com/cross-solution/cross-solution.de/commit/c7d8846b16280a8e2962ab8a0bf09dfcc30b6428

But this breaks the website in ssr mode. Do you have time to get this running in SSR mode?

## page in spa mode

`yarn dev`

![Auswahl_999(433)](https://user-images.githubusercontent.com/858642/97343997-76a3d780-1888-11eb-8f19-06883b0d3ee2.png)

## page in ssr mode

`yarn dev:ssr`

![Auswahl_999(434)](https://user-images.githubusercontent.com/858642/97344642-4f013f00-1889-11eb-8aae-2b488c332ca9.png)

**Comment by kilip** [comment]
Hello Carsten,

Yes, I can work om it. I will take a look at it today.

Regards,
Toni

**Comment by cbleek** [comment]
@kilip 

there is still an issue. (we've moved the celendly to another page, but I could see the behavior on the about page, too)

If I go th ou contact page. I can see the celendly.

https://cross-solution.de/contact 

But a shift reload in a browser leads to the following error in log syslog. Which ends in a "504 Gateway Time-out" of the nginx. I have no Idea how to debug this. Can you take once again some time and try to solve the issue?

```
Oct 29 19:38:38 quasar quasar[17694]: (node:17695) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
Oct 29 19:38:38 quasar quasar[17694]:     at server-bundle.js:1:16244
Oct 29 19:38:38 quasar quasar[17694]:     at Array.map (<anonymous>)
Oct 29 19:38:38 quasar quasar[17694]:     at server-bundle.js:1:16218
Oct 29 19:38:38 quasar quasar[17694]:     at /srv/cross-solution/releases/293/node_modules/vue-router/dist/vue-router.common.js:2096:11
Oct 29 19:38:38 quasar quasar[17694]:     at Array.forEach (<anonymous>)
Oct 29 19:38:38 quasar quasar[17694]:     at /srv/cross-solution/releases/293/node_modules/vue-router/dist/vue-router.common.js:2095:25
Oct 29 19:38:38 quasar quasar[17694]:     at /srv/cross-solution/releases/293/node_modules/vue-router/dist/vue-router.common.js:2210:7
Oct 29 19:38:38 quasar quasar[17694]:     at step (/srv/cross-solution/releases/293/node_modules/vue-router/dist/vue-router.common.js:1894:7)
Oct 29 19:38:38 quasar quasar[17694]:     at step (/srv/cross-solution/releases/293/node_modules/vue-router/dist/vue-router.common.js:1901:9)
Oct 29 19:38:38 quasar quasar[17694]: (node:17695) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by kilip** [comment]
@cbleek 

Looks like this problems only occurs in google chrome. I have tried to browse contact pages with firefox and it works nicely. I will try to integrate calendly using this instructions:

https://calendly.com/blog/product-update-embed-calendly-into-your-website/

![screenshot](https://user-images.githubusercontent.com/301065/97662576-6b33f480-1ab2-11eb-8703-d10e5bd9d498.png)

**Comment by cbleek** [comment]
No, same problem on my side. Using Firefox on Mac and Linux. Shift Reload 

But you're right. Maybe the vue-calendly is buggy. If you integrate it from scratch I prefer using the pop-up-text version.

https://calendly-embed.com/pop-up-text

**Comment by kilip** [comment]
@TiSiE @cbleek 

Looks like we can use calendly widget directly without components, by using this [code](https://github.com/cross-solution/cross-solution.de/pull/68/files#diff-4517e3cf87b5c3b73a8a93517a0b02cef309723564af9f5c316a4f377bab0676R71-R76):
```html
        <!-- Calendly inline widget begin -->
        <q-no-ssr>
          <div class="calendly-inline-widget" data-url="https://calendly.com/cross-solution" style="height:630px;"></div>
          <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js"></script>
        </q-no-ssr>
        <!-- Calendly inline widget end -->
```

**Comment by cbleek** [comment]
yes. It works. In Firefox and Chrome.

Can you show us, how to integrate it as pop-up-text version?

**Comment by cbleek** [comment]
Just found this in my calendly account. All we have to is to surround it with no-ssr. And "Zeitplan Zeitfenster" Text Link is shown.

@kilip I think, we have it. Thank you for helping us.

```
<!-- Calendly Link-Widget Beginn -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script>
<a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/cross-solution'});return false;">Zeitplan Zeitfenster</a>
<!-- Calendly Link-Widget Ende -->
```

**Comment by TiSiE** [comment]
@cbleek 
I found the reason for the problem, that the calendly popup is not shown on the production site but in your development environment:

On the production site, the script tag __is not__ rendered:
![calendly-script-missing](https://user-images.githubusercontent.com/2029304/97733722-8154ab80-1ad8-11eb-9abd-1ba7ab1e265b.png)

I have not figured out yet why that is, though....

**Comment by cbleek** [comment]
In the end I've simply added a link, which opens a new window.

Why simple, when it can also be complicated:-)

https://cross-solution.de/contact
