### ISSUE TITLE
Yawik Logo

### ISSUE THREAD

**Issue by cbleek** [cross-solution/cross-solution.de#75]
aus #31

@wkorolew kannst du mir folgendes Logo transparent groß mit 1024px und einmal nur das y im Keis auch groß mit 1024 px machen?

https://user-images.githubusercontent.com/55985319/71089793-db3ed200-21a1-11ea-91e0-d091c44d7b35.png

**Comment by wkorolew** [comment]
anbei das Logo yawik lang & short:

als PNG 1024px


![yawik_logo_1024](https://user-images.githubusercontent.com/55985319/104595076-5ce98380-5672-11eb-93ca-7dbc96683b30.png)
![yawik_logo_circle](https://user-images.githubusercontent.com/55985319/104595079-5d821a00-5672-11eb-92f3-0269fcf0e7c3.png)

ZIP mit SVGs:

[yawik.zip](https://github.com/cross-solution/cross-solution.de/files/5814582/yawik.zip)

=> spend/0.45min

**Comment by cbleek** [comment]
Perfekt!

für mich zur Erinnerung ....
```
cbleek@xenon:~/temp/Yawik$ icongenie g  -p spa -s yawik_logo_circle.png -t yawik-circle/
no minify strategyns                          
cbleek@xenon:~/temp/Yawik$ icongenie g  -p spa -s yawik_logo_1024.png -t yawik-1024/
no minify strategyns  
```
